window:
  dimensions:
    columns: 120
    lines: 50

  # opacity: 0.99999
  # バグ回避: https://github.com/alacritty/alacritty/issues/4474

font:
  normal:
    family: Hack
  size: 13.0

live_config_reload: true

# Colors (Tomorrow Night)
colors:
  # Default colors
  primary:
    background: '#1d1f21'
    foreground: '#c5c8c6'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#1d1f21'
    cursor: '#ffffff'

  # Normal colors
  normal:
    black:   '#1d1f21'
    red:     '#cc6666'
    green:   '#b5bd68'
    yellow:  '#e6c547'
    blue:    '#81a2be'
    magenta: '#b294bb'
    cyan:    '#70c0ba'
    white:   '#373b41'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#9ec400'
    yellow:  '#f0c674'
    blue:    '#81a2be'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#282a2e'
