cask_args appdir: '/Applications'
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "itchyny/tap"

brew "bat"
brew "cmigemo"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "graphviz"
brew "im-select"
brew "itchyny/tap/mmv"
brew "jupyterlab"
brew "macism"
brew "mas"
brew "neovim"
brew "node"
brew "pandoc"
brew "python"
brew "r"
brew "radian"
brew "ripgrep"
brew "ruby"
brew "sd"
brew "tig"
brew "trash"
brew "vim"
brew "yq"
brew "z"

cask "appcleaner"
cask "aquaskk"
cask "arc"
cask "bettertouchtool"
cask "bike"
cask "box-drive"
cask "cleanshot"
cask "coteditor"
cask "cron"
cask "discord"
cask "dropbox"
cask "google-chrome"
cask "google-drive"
cask "karabiner-elements"
cask "linear-linear"
cask "logi-options-plus"
cask "microsoft-office"
cask "pushplaylabs-sidekick"
cask "qmk-toolbox"
cask "raycast"
cask "rectangle"
cask "rstudio"
cask "scroll-reverser"
cask "slack"
cask "superhuman"
cask "the-unarchiver"
cask "todoist"
cask "visual-studio-code"
cask "vlc"
cask "workflowy"
cask "zoom"

cask "font-cantarell"
cask "font-hack"
cask "font-inconsolata"
cask "font-lato"
cask "font-noto-sans-jp"
cask "font-noto-serif-jp"

mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Keepa - Price Tracker", id: 1533805339
mas "LINE", id: 539883307
mas "Save to Raindrop.io", id: 1549370672
mas "Textwell", id: 905944937
mas "Yoink", id: 457622435
