cask_args appdir: '/Applications'
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"

brew "bat"
brew "cmigemo"
brew "docker"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "github/gh/gh"
brew "go"
brew "graphviz"
brew "hub"
brew "itchyny/tap/mmv"
brew "jupyterlab"
brew "mackup"
brew "macvim"
brew "mas"
brew "node"
brew "pandoc"
brew "python"
brew "r"
brew "ripgrep"
brew "rmtrash"
brew "ruby"
brew "sd"
brew "tig"
brew "tmux"
brew "z"

cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "bitwarden"
cask "box-drive"
cask "coteditor"
cask "dash"
cask "discord"
cask "docker"
cask "github"
cask "gitup"
cask "google-chrome"
cask "google-drive-file-stream"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "kindle"
cask "logitech-options"
cask "microsoft-office"
cask "rstudio"
cask "scroll-reverser"
cask "slack"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"

cask "font-cantarell"
cask "font-dejavu-sans"
cask "font-hack"
cask "font-inconsolata"
cask "font-lato"
cask "font-noto-sans-cjk-jp"
cask "font-noto-serif-cjk-jp"
cask "font-source-code-pro"
cask "font-source-han-code-jp"

mas "Amphetamine", id: 937984704
mas "Gravit Designer", id: 1207744923
mas "LINE", id: 539883307
mas "Textwell", id: 905944937
mas "Yoink", id: 457622435
