vim9script

#
# .vimrc
#

# SETUP {{{

set encoding=utf-8
scriptencoding utf-8
set fileencoding=utf-8
set fileencodings=utf-8,sjis,euc-jp,iso-2022-jp,cp932
set fileformats=unix,dos,mac

filetype plugin indent on
syntax enable

language messages en_US.UTF-8
language time en_US.UTF-8

augroup vimrc
  autocmd!
augroup END

unlet! g:skip_defaults_vim
source $VIMRUNTIME/defaults.vim

g:no_vimrc_example  = 1
g:no_gvimrc_example = 1

if has('gui_macvim')
  g:macvim_skip_colorscheme      = 1
  g:macvim_skip_cmd_opt_movement = 1
endif

g:did_install_default_menus = 1
g:did_install_syntax_menu   = 1
g:loaded_2html_plugin       = 1
g:loaded_getscript          = 1
g:loaded_getscriptPlugin    = 1
g:loaded_gzip               = 1
g:loaded_netrw              = 1
g:loaded_netrwFileHandlers  = 1
g:loaded_netrwPlugin        = 1
g:loaded_netrwSettings      = 1
g:loaded_rrhelper           = 1
g:loaded_tar                = 1
g:loaded_tarPlugin          = 1
g:loaded_vimball            = 1
g:loaded_vimballPlugin      = 1
g:loaded_zip                = 1
g:loaded_zipPlugin          = 1
g:skip_loading_mswin        = 1

# }}}

# OPTIONS {{{

# Edit {{{

set hidden
set autoread
set switchbuf=usetab,uselast

set noswapfile
set nowritebackup

set shell=fish
set history=10000
set helplang=ja
set spelllang+=cjk
set clipboard=unnamed,unnamedplus

set virtualedit=onemore
set whichwrap=b,s,h,l,<,>,[,]
set autochdir

set autoindent
set smartindent
set breakindent

set expandtab
set smarttab
set shiftround
set tabstop=2
set shiftwidth=0
set softtabstop=-1

augroup vimrc
  autocmd FileType julia  setlocal tabstop=4
  autocmd FileType python setlocal tabstop=4
  autocmd FileType rust   setlocal tabstop=4
  autocmd FileType go     setlocal tabstop=4 noexpandtab
  autocmd BufRead,BufNewFile *.tsv setlocal tabstop=8 noexpandtab
augroup END

set formatoptions+=jro
set formatoptions-=c

augroup vimrc
  autocmd FileType markdown setlocal comments=b:-,b:+,b:*,b:1.,nb:>
  autocmd FileType typst    setlocal comments=b:-,b:+
  autocmd FileType r        setlocal comments=b:#
augroup END

set foldmethod=marker

set diffopt=
      \algorithm:histogram,
      \closeoff,
      \filler,
      \indent-heuristic,
      \inline:char,
      \internal,
      \linematch:60,
      \vertical

# }}}

# View {{{

set title
set number
set signcolumn=yes
set list
set listchars=tab:≫\ ,trail:\ ,nbsp:~,extends:▶,precedes:◀

set display=lastline
set sidescroll=1
set scrolloff=0
set sidescrolloff=1

set updatetime=100
set belloff=all
set cursorline

set noshowmatch
set matchtime=0
set matchpairs+=（:）,「:」,『:』,〈:〉,《:》,【:】,〔:〕,［:］,｛:｝,‘:’,“:”

set noshowmode
set shortmess+=cmrF
set shortmess-=S

set statusline=%!SetStatusLine()
set laststatus=2
set fillchars=vert:│,fold:·,foldsep:│,eob:·

set termguicolors

# -- True Color
&t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
&t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

# -- Undercurl
&t_Cs = "\e[4:3m"
&t_Ce = "\e[4:0m"

if has('vim_starting')
  # -- Corsor Style
  &t_SI ..= "\e[6 q"
  &t_SR ..= "\e[4 q"
  &t_EI ..= "\e[2 q"
endif

# }}}

# Search & Replace {{{

set hlsearch
set ignorecase
set smartcase
set gdefault

if executable('rg')
  &grepprg = 'rg --vimgrep --smart-case'
  set grepformat=%f:%l:%c:%m
endif

# }}}

# Completion {{{

# -- Insert Mode
set complete+=o
set completeopt=menuone,noinsert
set autocomplete
set autocompletedelay=300
set pumopt=height:20

# -- Cmdline Mode
set wildmode=noselect:lastused,full
set wildoptions=pum,fuzzy

# }}}

# }}}

# KEYMAPS {{{

# :map Commands {{{

#        Norm   Ins   Cmd   Vis   Sel   Opr   Term   Lang
#       ------ ----- ----- ----- ----- ----- ------ ------
# map    yes     -     -    yes   yes   yes    -      -
# map!    -     yes   yes    -     -     -     -      -
# nmap   yes     -     -     -     -     -     -      -
# imap    -     yes    -     -     -     -     -      -
# cmap    -      -    yes    -     -     -     -      -
# vmap    -      -     -    yes   yes    -     -      -
# xmap    -      -     -    yes    -     -     -      -
# smap    -      -     -     -    yes    -     -      -
# omap    -      -     -     -     -    yes    -      -
# tmap    -      -     -     -     -     -    yes     -
# lmap    -     yes   yes    -     -     -     -     yes

# }}}

# General {{{

g:mapleader = ','
g:maplocalleader = '\'

noremap ; :
noremap : ;
noremap j gj
noremap k gk
noremap gj j
noremap gk k
noremap x "_x
noremap X "_X

nnoremap Y y$
nnoremap & :&&<CR>

inoremap <C-u> <C-g>u<C-u>
inoremap <C-w> <C-g>u<C-w>

noremap + <C-a>
noremap - <C-x>
noremap g+ g<C-a>
noremap g- g<C-x>

nnoremap U <C-r>
nnoremap <C-h> <C-^>
nnoremap <BS>  <C-^>

nnoremap <C-;> <Cmd>nohlsearch <Bar> redraw!<CR>

inoremap <C-a> <Cmd>normal! ^<CR>
inoremap <C-e> <Cmd>normal! $l<CR>

cnoremap <C-a> <C-b>
cnoremap <C-x> <C-r>=expand('%:p')<CR>

# }}}

# Completion {{{

inoremap <expr> <CR>    pumvisible() ? '<C-y>' : '<CR>'
inoremap <expr> <TAB>   pumvisible() ? '<C-n>' : '<C-t>'
inoremap <expr> <S-TAB> pumvisible() ? '<C-p>' : '<C-d>'

cnoremap <expr> <Up>   wildmenumode() ? '<C-e><Up>'   : '<Up>'
cnoremap <expr> <Down> wildmenumode() ? '<C-e><Down>' : '<Down>'

# }}}

# Window {{{

nmap t <C-w>
nnoremap <C-w>t <C-w>w
nnoremap <C-w>. <Cmd>bnext<CR>
nnoremap <C-w>, <Cmd>bprevious<CR>

nmap <C-w>+ <C-w>+<SID>ws
nmap <C-w>- <C-w>-<SID>ws
nmap <C-w>> <C-w>><SID>ws
nmap <C-w>< <C-w><<SID>ws
nnoremap <script> <SID>ws+ <C-w>+<SID>ws
nnoremap <script> <SID>ws- <C-w>-<SID>ws
nnoremap <script> <SID>ws> <C-w>><SID>ws
nnoremap <script> <SID>ws< <C-w><<SID>ws
nmap <SID>ws <Nop>

# }}}

# .vimrc {{{

nnoremap <Leader>, <Cmd>edit $MYVIMRC<CR>
nnoremap <Leader>. <Cmd>ReloadVimrc<CR>
nnoremap <Leader>/ <Cmd>edit $HOME/dotfiles/vim/config<CR>

command! ReloadVimrc {
  source $MYVIMRC
  if has('gui_running')
    source $MYGVIMRC
  endif
  nohlsearch
  redraw!
}

# }}}

# Markdown {{{

augroup vimrc
  autocmd FileType markdown inoremap <buffer> <Tab>   <C-t>
  autocmd FileType markdown inoremap <buffer> <S-Tab> <C-d>
  autocmd FileType markdown inoremap <buffer> <C-d>   <Delete>
augroup END

# }}}

# zz -> zz, zt, zb... {{{

nmap zz zz<SID>(z1)
nnoremap <script> <SID>(z1)z zt<SID>(z2)
nnoremap <script> <SID>(z2)z zb<SID>(z3)
nnoremap <script> <SID>(z3)z zz<SID>(z1)

# }}}

# f -> z {{{

nmap f z
nnoremap F f

nmap zf zz
nnoremap <script> <SID>(z1)f zt<SID>(z2)
nnoremap <script> <SID>(z2)f zb<SID>(z3)
nnoremap <script> <SID>(z3)f zz<SID>(z1)

# }}}

# <Space> Leader {{{

# noremap <Space>l <Cmd>nohlsearch <Bar> redraw!<CR>
# noremap <expr> <Space>s <SID>substitute_last_search()

# nnoremap <Space>w <Cmd>update<CR>
# nnoremap <Space>q <Cmd>quit<CR>

# }}}

# Nop {{{

noremap ZZ    <Nop>
noremap ZQ    <Nop>
noremap Q     <Nop>
noremap gQ    <Nop>
noremap <Del> <Nop>

noremap  <C-j> <Nop>
noremap  <C-l> <Nop>
noremap! <C-j> <Nop>
noremap! <C-l> <Nop>

inoremap <D-a> <Nop>
inoremap <D-i> <Nop>

inoremap <D-0> <Nop>
inoremap <D-1> <Nop>
inoremap <D-2> <Nop>
inoremap <D-3> <Nop>
inoremap <D-4> <Nop>
inoremap <D-5> <Nop>
inoremap <D-6> <Nop>
inoremap <D-7> <Nop>
inoremap <D-8> <Nop>
inoremap <D-9> <Nop>

map <LeftMouse>   <Nop>
map <RightMouse>  <Nop>
map <MiddleMouse> <Nop>
map <2-LeftMouse> <Nop>
map <3-LeftMouse> <Nop>
map <4-LeftMouse> <Nop>

imap <LeftMouse>   <Nop>
imap <RightMouse>  <Nop>
imap <MiddleMouse> <Nop>
imap <2-LeftMouse> <Nop>
imap <3-LeftMouse> <Nop>
imap <4-LeftMouse> <Nop>

# }}}

# }}}

# AUTO COMMANDS {{{

# Filetype {{{

augroup vimrc
  autocmd FileType gitcommit setlocal fileencoding=utf-8
  autocmd BufRead,BufNewFile *.{txt,text} setlocal filetype=markdown
  autocmd BufRead,BufNewFile *.typ setlocal filetype=typst
  autocmd BufRead,BufNewFile *.keymap setlocal filetype=dts tabstop=4
augroup END

# }}}

# Quit by q {{{

augroup vimrc
  autocmd FileType help,qf,man,ref,diff,quickrun nnoremap <buffer> q <Cmd>quit!<CR>
  autocmd QuickFixCmdPost *grep*,make {
    if len(getqflist()) != 0
      cwindow
    endif
  }
augroup END

# }}}

# Diff Mode {{{

autocmd vimrc VimEnter,DiffUpdated * {
  if &diff
    setlocal nospell
    setlocal wrap<
  endif
}

# }}}

# Auto IME On/Off {{{

# IME の切り替えには macism を使う
# osascript 経由で AppleScript/JavaScript を使うと macism より遅くなる

var ime_cmd  = 'macism'
var en_ime   = 'net.mtgto.inputmethod.macSKK.ascii'
var ja_ime   = 'net.mtgto.inputmethod.macSKK.hiragana'
var prev_ime = en_ime

# -- Auto IME Off
augroup vimrc
  autocmd VimEnter,VimResume,FocusGained * ImeOff()
  autocmd InsertLeave * ImeOff()
augroup END

# -- Auto IME On/Off
# Insert mode を抜けた後、macism の実行を待つ間、
# 少しの時間キー入力を受け付けなくなる問題がある
# これは system() の代わりに job_start() を使っても同じである
#
# augroup vimrc
#   autocmd VimEnter,VimResume,FocusGained * ImeOff()
#   autocmd InsertLeave * SaveImeAndImeOff()
#   autocmd InsertEnter * RestoreIme()
# augroup END

def ImeOff(): void
  job_start([ime_cmd, en_ime], {'stoponexit': ''})
enddef

def ImeOn(): void
  job_start([ime_cmd, ja_ime], {'stoponexit': ''})
enddef

def RestoreIme(): void
  if prev_ime == ja_ime
    ImeOn()
  endif
enddef

def SaveImeAndImeOff(): void
  prev_ime = trim(system(ime_cmd))
  ImeOff()
enddef

# }}}

# Auto Completion in Cmdline {{{

augroup vimrc
  autocmd CmdlineChanged [:] wildtrigger()
  autocmd CmdlineEnter [:] set pumopt=height:10
  autocmd CmdlineLeave [:] set pumopt=height:20
augroup END

# -- Cmdline の補完候補が選択されているときには確定、
#    選択されていないときには一番上の候補を選択して確定する
cnoremap <expr> <Tab> <SID>CmdcompleteSelected() ? '<CR>' : '<C-n><CR>'

# -- Cmdline の補完候補が選択されているかを判定する関数
def CmdcompleteSelected(): bool
  var info = cmdcomplete_info()
  var unselected = info == {} || info['selected'] == -1
  return !unselected
enddef

# }}}

# MTGAP Mappings {{{

var saved_mappings: list<dict<string>>

# augroup vimrc
#   autocmd VimEnter * MtgapOn()
# augroup END

command! MtgapOn  MtgapOn()
command! MtgapOff MtgapOff()

def MtgapOn()
  saved_mappings = maplist()

  # Normal Mode {{{
  nmap y gr
  nmap Y gR

  nmap j <C-w>
  nnoremap <C-w>j <C-w>w
  nnoremap <C-w>m <C-w>h
  nnoremap <C-w>h <C-w>j
  nnoremap <C-w>t <C-w>k
  nnoremap <C-w>s <C-w>l
  nnoremap <C-w>M <C-w>H
  nnoremap <C-w>H <C-w>J
  nnoremap <C-w>T <C-w>K
  nnoremap <C-w>S <C-w>L

  nmap k   <Plug>(sandwich-add)
  nmap K   <Plug>(sandwich-add)$
  nmap kd  <Plug>(sandwich-delete)
  nmap kdb <Plug>(sandwich-delete-auto)
  nmap kc  <Plug>(sandwich-replace)
  nmap kcb <Plug>(sandwich-replace-auto)

  nnoremap d y
  nnoremap D y$
  nnoremap l d
  nnoremap L D

  nnoremap m h
  nnoremap h gj
  nnoremap H L
  nnoremap t gk
  nnoremap T H
  nnoremap s l
  nnoremap S K

  # silent! nunmap f
  # silent! nunmap zf
  # }}}
  # Visual Mode {{{
  xmap y  gr
  xmap Y  gR

  xmap j t
  xmap J T

  xmap k  <Plug>(sandwich-add)
  xmap K  <Plug>(sandwich-add)$
  xmap kd <Plug>(sandwich-delete)
  xmap kc <Plug>(sandwich-replace)

  xnoremap d y
  xnoremap D y$
  xnoremap l d
  xnoremap L D

  xnoremap m h
  xnoremap h gj
  xnoremap H L
  xnoremap t gk
  xnoremap T H
  xnoremap s l
  xnoremap S K
  # }}}
  # Operator-pending Mode {{{
  omap y <Nop>
  omap Y <Nop>

  omap j t
  omap J T

  omap k <Plug>(sandwich-add)
  omap K <Plug>(sandwich-add)$

  onoremap d y
  onoremap D y$
  onoremap l d
  onoremap L D

  onoremap m h
  onoremap h gj
  onoremap H L
  onoremap t gk
  onoremap T H
  onoremap s l
  onoremap S K
  # }}}
enddef

def MtgapOff()
  if empty(saved_mappings)
    echohl ErrorMsg
    echomsg 'MtgapOff: 保存されたマッピングがありません'
    echohl None
    return
  endif

  mapclear

  for m in saved_mappings
    mapset(m)
  endfor
enddef

# }}}

# }}}

# COMMANDS & FUNCTIONS {{{

# Check Back Space (global) {{{

def g:CheckBackSpace(): bool
  var col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
enddef

# }}}

# Set Status Line (global) {{{

var mode_map = {
  n:       '  NORMAL ',
  i:       '  INSERT ',
  R:       ' REPLACE ',
  v:       '  VISUAL ',
  V:       '  V-LINE ',
  '<C-v>': ' V-BLOCK ',
  c:       ' COMMAND ',
  s:       '  SELECT ',
  S:       '  S-LINE ',
  '<C-s>': ' S-BLOCK ',
  t:       ' TERMINAL '
}

def g:GetMode(): string
  return get(mode_map, mode(), '')
enddef

def g:SetStatusLine(): string
  var fenc = &fileencoding != '' ? &fileencoding : &encoding
  var ft   = &filetype     != '' ? &filetype     : 'no ft'

  var percentage: string
  var lines: string
  var cols: string

  # Percent
  var pct_num = line('.') * 100 / line('$')
  if pct_num < 10
    percentage = '     ' .. pct_num .. '%%'
  elseif pct_num < 100
    percentage = '    ' .. pct_num .. '%%'
  else
    percentage = '   ' .. pct_num .. '%%'
  endif

  # Lines
  if line('.') < 10
    lines = '    %l:'
  elseif line('.') < 100
    lines = '   %l:'
  else
    lines = '  %l:'
  endif

  # Columns
  if col('.') < 10
    cols = '%c   '
  elseif col('.') < 100
    cols = '%c  '
  else
    cols = '%c '
  endif

  return g:GetMode() ..
    '| %t %m' ..
    '%=' ..
    '%{&fileformat}' .. ' | ' .. fenc .. ' | ' .. ft ..
    percentage .. lines .. cols
enddef

# }}}

# DiffOrig (tweaked) {{{

command! DiffOrig DiffOrig()

def DiffOrig()
    var orig_buf = bufnr('%')
    vertical new
    set buftype=nofile filetype=diff
    execute 'read ++edit #' .. orig_buf
    execute '0delete _'
    diffthis
    wincmd p
    diffthis
enddef

# }}}

# Insert Blank Lines {{{

nnoremap <expr> go <SID>BlankBelow()
nnoremap <expr> gO <SID>BlankAbove()

def BlankBelow(type = ''): string
  if type == ''
    &operatorfunc = BlankBelow
    return 'g@ '
  endif

  for i in range(v:count1)
    append('.', '')
  endfor
  return ''
enddef

def BlankAbove(type = ''): string
  if type == ''
    &operatorfunc = BlankAbove
    return 'g@ '
  endif

  for i in range(v:count1)
    append(line('.') - 1, '')
  endfor
  return ''
enddef

# }}}

# Vertical Help {{{

nnoremap gK <ScriptCmd>HelpVerticalCword()<CR>
xnoremap gK <ScriptCmd>HelpVerticalSelected()<CR>

def HelpVerticalCword(): void
  var word = expand('<cword>')
  if word != ''
    execute 'vertical help' word
  endif
enddef

def HelpVerticalSelected(): void
  execute 'silent normal! "vy'
  var word = @v
  execute 'vertical help' word
enddef

# }}}

# Syntax Info {{{

command! SyntaxInfo GetSynInfo()

def GetSynId(transparent: bool): number
  var synid = synID('.', col('.'), 1)
  if transparent
    return synIDtrans(synid)
  else
    return synid
  endif
enddef

def GetSynAttr(synid: number): dict<string>
  var name    = synIDattr(synid, 'name')
  var ctermfg = synIDattr(synid, 'fg', 'cterm')
  var ctermbg = synIDattr(synid, 'bg', 'cterm')
  var guifg   = synIDattr(synid, 'fg', 'gui')
  var guibg   = synIDattr(synid, 'bg', 'gui')
  return {
    'name':    name,
    'ctermfg': ctermfg,
    'ctermbg': ctermbg,
    'guifg':   guifg,
    'guibg':   guibg
  }
enddef

def GetSynInfo(): void
  var baseSyn = GetSynAttr(GetSynId(0))
  echo
    'name: '     .. baseSyn.name ..
    ' ctermfg: ' .. baseSyn.ctermfg ..
    ' ctermbg: ' .. baseSyn.ctermbg ..
    ' guifg: '   .. baseSyn.guifg ..
    ' guibg: '   .. baseSyn.guibg
  var linkedSyn = GetSynAttr(GetSynId(1))
  echo 'link to'
  echo
    'name: '     .. linkedSyn.name ..
    ' ctermfg: ' .. linkedSyn.ctermfg ..
    ' ctermbg: ' .. linkedSyn.ctermbg ..
    ' guifg: '   .. linkedSyn.guifg ..
    ' guibg: '   .. linkedSyn.guibg
enddef

# }}}

# Timestamp {{{

augroup vimrc
  autocmd FileType markdown
        \ nnoremap <buffer> <Leader>d <ScriptCmd>TimestampBelow()<CR>
  autocmd FileType markdown
        \ nnoremap <buffer> <Leader>D <ScriptCmd>TimestampAbove()<CR>
augroup END

def SetTimestamp(): string
  var timestamp = '## ' .. strftime('%Y-%m-%d %H:%M:%S')
  return timestamp
enddef

def TimestampBelow(): void
  var timestamp = SetTimestamp()

  if strlen(getline('.')) > 0
    append('.', ['', timestamp, ''])
    cursor(line('.') + 3, 1)
  elseif strlen(getline(line('.') - 1)) > 0
    append('.', [timestamp, ''])
    cursor(line('.') + 2, 1)
  else
    append(line('.') - 1, timestamp)
  endif
  startinsert
enddef

def TimestampAbove(): void
  var timestamp = SetTimestamp()

  if strlen(getline('.')) > 0
    append(line('.') - 1, timestamp)
  else
    setline('.', timestamp)
  endif
enddef

# }}}

# Zk Journal {{{

nnoremap <Leader>m <Nop>
nnoremap [zk] <Nop>
nmap <Leader>m [zk]
nnoremap [zk]n <ScriptCmd>OpenJournalFile()<CR>
nnoremap [zk]j <ScriptCmd>OpenJournalDir()<CR>

var zk_dir = expand('$ZK_NOTEBOOK_DIR')
var journal_dir = zk_dir .. '/journal'

def OpenJournalFile(): void
  var file_name = strftime('%Y-%m-%d') .. '.md'
  var file_path_pattern = 'zk/journal/' .. file_name
  var win_id = bufwinid(file_path_pattern)

  if win_id > 0
    win_gotoid(win_id)
  else
    execute 'edit' journal_dir .. '/' .. file_name
  endif
enddef

def OpenJournalDir(): void
  execute 'edit' journal_dir
enddef

# }}}

# Cd Current File {{{

command! CdCurrentFile lcd %:h

# }}}

# Print tabstop, shiftwidth, softtabstop {{{

nnoremap <Leader>a <ScriptCmd>PrintIndents()<CR>
command! PrintIndents PrintIndents()

def PrintIndents(): void
  var ts = &tabstop
  var sw = &shiftwidth
  var sts = &softtabstop
  echo 'tabstop: ' .. ts .. ', shiftwidth: ' .. sw .. ', softtabstop: ' .. sts
enddef

# }}}

# Fill Line {{{

command! FillLine FillLine()

def FillLine(): void
  var width = 50
  var str = substitute(getline('.'), ' \+$', '', '')
  var display_width = strdisplaywidth(str)
  var sep_len = width - display_width - 1
  if sep_len < 1
    sep_len = 1
  endif
  var sep = repeat('-', sep_len)
  setline('.', str .. ' ' .. sep)
enddef

# }}}

# Substitute with Last Search {{{

def SubstituteLastSearch(): void
  var cmd = mode() =~# "[vV\<C-v>]" ? ':s/' : ':%s/'
  feedkeys(cmd .. @/ .. "//\<Left>", 'n')
enddef

# }}}

# No/Restore Status Line {{{

command! NoStatusLine      NoStatusline()
command! RestoreStatusLine RestoreStatusline()
command! ToggleStatusline  ToggleStatusline()

var saved_hl_statusline: list<dict<any>>

def NoStatusline(): void
  saved_hl_statusline = hlget('StatusLine')

  highlight! link StatusLine VertSplit
  highlight! link StatusLineNC VertSplit

  set statusline=─
  set laststatus=0
  set fillchars=stl:─,stlnc:─,vert:│,fold:·,foldsep:│,eob:·
  set noruler
enddef

def RestoreStatusline(): void
  hlset(saved_hl_statusline)

  set statusline=%!SetStatusLine()
  set laststatus=2
  set fillchars=vert:│,fold:·,foldsep:│,eob:·
  set ruler

  saved_hl_statusline = []
enddef

def ToggleStatusline(): void
  if empty(saved_hl_statusline)
    NoStatusline()
  else
    RestoreStatusline()
  endif
enddef

# }}}

# }}}

# PLUGINS {{{

# Vim-Plug {{{

g:data_dir = '~/.vim'
if empty(glob(g:data_dir .. '/autoload/plug.vim'))
  silent execute '!curl -fLo ' .. g:data_dir .. '/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

plug#begin('~/.vim/plugged')

nnoremap <Leader>p <Nop>
nnoremap [plug] <Nop>
nmap <Leader>p [plug]

nnoremap [plug]s <Cmd>PlugStatus<CR>
nnoremap [plug]i <Cmd>PlugInstall<CR>
nnoremap [plug]c <Cmd>PlugClean<CR>
nnoremap [plug]u <Cmd>PlugUpdate<CR>
nnoremap [plug]g <Cmd>PlugUpgrade<CR>

# }}}

# Library {{{

Plug 'vim-denops/denops.vim'

# }}}

# LSP {{{

Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'mattn/vim-lsp-icons'

Plug 'dense-analysis/ale'
Plug 'rhysd/vim-lsp-ale'

# }}}

# Completion {{{

# Plug 'prabirshrestha/asyncomplete.vim'
# Plug 'prabirshrestha/asyncomplete-buffer.vim'
# Plug 'prabirshrestha/asyncomplete-file.vim'
# Plug 'prabirshrestha/asyncomplete-lsp.vim'

# }}}

# Fuzzy Finder {{{

set runtimepath+=/opt/homebrew/opt/fzf
Plug 'junegunn/fzf.vim'
# Plug 'ctrlpvim/ctrlp.vim'
# Plug 'mattn/ctrlp-matchfuzzy'

# }}}

# Language Support {{{

g:polyglot_disabled = ['autoindent', 'sensible', 'csv', 'markdown', 'r-lang']
Plug 'sheerun/vim-polyglot'

Plug 'fladson/vim-kitty',       #{ for: 'kitty' }
Plug 'jalvesaq/Nvim-R',         #{ for: 'r' }
Plug 'kaarmu/typst.vim',        #{ for: 'typst' }
Plug 'mechatroner/rainbow_csv', #{ for: 'csv' }
Plug 'rcmdnk/vim-markdown',     #{ for: 'markdown' }
Plug 'vim-jp/syntax-vim-ex',    #{ for: 'vim' }

# Haskell {{{

# Plug 'alx741/vim-hindent',         #{ for: 'haskell' }
# Plug 'itchyny/vim-haskell-indent', #{ for: 'haskell' }
Plug 'neovimhaskell/haskell-vim',  #{ for: 'haskell' }

# }}}

# Lisp {{{

# Plug 'guns/vim-sexp',                              { for: ['scheme', 'clojure'] }
# Plug 'liquidz/dps-parinfer',                       { for: ['scheme', 'clojure'] }
# Plug 'luochen1990/rainbow',                        { for: ['scheme', 'clojure'] }
# Plug 'tpope/vim-sexp-mappings-for-regular-people', { for: ['scheme', 'clojure'] }

# }}}

# Numbat {{{

# https://github.com/sharkdp/numbat/blob/master/assets/numbat.vim
# Numbat.vim - Vim syntax file for Numbat language

if exists("b:current_syntax")
  finish
endif

# Numbat Keywords
syn keyword numbatKeywords per to let fn where and dimension unit use struct long short both none if then else true false NaN inf print assert assert_eq type
highlight default link numbatKeywords Keyword

# Physical dimensions (every capitalized word)
syn match numbatDimensions "\<\u\w*\>"
highlight default link numbatDimensions Type

# Variables and units (lowercase words)
# syn match numbatIdentifier "\<\l\w*\>"
# highlight default link numbatIdentifier Identifier

# Comments
syn match numbatComments "#.*"
highlight default link numbatComments Comment

# Digits/Numbers
syn match numbatNumber '\v<0x[0-9a-fA-F]+>'
syn match numbatNumber '\v<0o[0-7]+>'
syn match numbatNumber '\v<0b[01]+>'
syn match numbatNumber '\v<[0-9]+(_[0-9]+)*([eE][+-]?[0-9]+)?>'
syn match numbatNumber '\v<([0-9]*\.[0-9]*|[0-9]*\.[0-9]+)([eE][+-]?[0-9]+)?>'
highlight default link numbatNumber Number

# Operators
syn match numbatOperators "->\|[+*^=/\-:·⋅×÷²³<>]"
highlight default link numbatOperators Operator

# Unit decorators
syn match numbatDecorator "@\w\+"
highlight default link numbatDecorator Constant

# Special units
syn match numbatSpecialUnits "[\u00B0]"  # degree symbol
highlight default link numbatSpecialUnits SpecialChar

# Strings
syntax match numbatString /"\([^"]*\)"/
highlight link numbatString String

# Load the matchit.vim script for the "%" matching, if it's available
if exists(":DoMatchIt")
  DoMatchIt
endif

setlocal comments=b:#,fb:-
setlocal commentstring=#\ %s

b:current_syntax = "numbat"

# }}}

# }}}

# Edit {{{

Plug 'AndrewRadev/linediff.vim'
Plug 'alvan/vim-closetag'
Plug 'chrisbra/NrrwRgn'
Plug 'cohama/lexima.vim'
Plug 'godlygeek/tabular'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'kana/vim-niceblock'
Plug 'kana/vim-repeat'
Plug 'kana/vim-smartchr'
Plug 'machakann/vim-sandwich'
Plug 'mattn/vim-maketable'
Plug 'rcmdnk/yankround.vim'
Plug 'thinca/vim-quickrun'
# Plug 'vimoutliner/vimoutliner'

Plug 'prettier/vim-prettier', #{
      \ do: 'yarn install --frozen-lockfile --production',
      \ for: ['html', 'css', 'less', 'scss'],
      \ }

# -- Must be set before 'packadd comment'
g:comment_mappings = false

packadd! comment
packadd! matchit

# Comment.vim Config {{{
nmap <Leader>c  <Plug>(comment-toggle)
xmap <Leader>c  <Plug>(comment-toggle)
nmap <Leader>cc <Plug>(comment-toggle-line)
nmap <Leader>C  <Plug>(comment-toggle-end)

omap ic <Plug>(comment-text-object-inner)
omap ac <Plug>(comment-text-object-outer)
xmap ic <Plug>(comment-text-object-inner)
xmap ac <Plug>(comment-text-object-outer)
# }}}

# }}}

# View {{{

Plug 'itchyny/vim-highlighturl'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/vim-peekaboo'
# Plug 'lambdalisue/glyph-palette.vim'
# Plug 'lambdalisue/nerdfont.vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'rbtnn/vim-ambiwidth'

Plug 'delphinus/vim-auto-cursorline'
Plug 'mhinz/vim-signify'

packadd! hlyank

# Highlight-Yank Config {{{
g:hlyank_hlgroup = 'Visual'
g:hlyank_duration = 300
g:hlyank_invisual = false
# }}}

# }}}

# Move {{{

# Plug 'MattesGroeger/vim-bookmarks'
Plug 'cocopon/vaffle.vim'
Plug 'haya14busa/vim-edgemotion'
Plug 'junegunn/vim-slash'
# Plug 'kana/vim-smartword'
# Plug 'mattn/vim-findroot'
Plug 'tyru/open-browser.vim'
Plug 'yuki-yano/fuzzy-motion.vim'

# }}}

# Operator & Text Object {{{

Plug 'kana/vim-operator-user'
Plug 'kana/vim-textobj-user'

Plug 'kana/vim-operator-replace'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-line'

# }}}

# Japanese Support {{{

Plug 'deton/jasegment.vim'
Plug 'deton/jasentence.vim'
# Plug 'lambdalisue/kensaku-search.vim'
# Plug 'lambdalisue/kensaku.vim'
Plug 'mattn/learn-vimscript'
Plug 'vim-jp/vimdoc-ja'

# }}}

# Colorscheme {{{

Plug 'cocopon/iceberg.vim'
Plug 'nordtheme/vim'
Plug 'rose-pine/vim'
Plug 'sainnhe/edge'
Plug 'sainnhe/everforest'
Plug 'sainnhe/gruvbox-material'
Plug 'sainnhe/sonokai'

# }}}

# Vim-Plug plug#end {{{

plug#end()

# }}}

# Config {{{

# -- Colorscheme Config
runtime! config/colorscheme.vim

# -- Plugin Config
var plugs = get(g:, 'plugs', {})

def g:FindPlugin(name: string): number
  return has_key(plugs, name) ? isdirectory(plugs[name].dir) : 0
enddef

command! -nargs=1 UsePlugin {
  if !g:FindPlugin(<args>)
    finish
  endif
}

runtime! config/config-*.vim

# }}}

# }}}

defcompile
