# zk configuration file

# NOTEBOOK SETTINGS
[notebook]
dir = "~/Library/CloudStorage/Box-Box/Journal"

# NOTE SETTINGS
[note]
language = "en"
default-title = "Untitled"
filename = "{{format-date now}}"
extension = "bike"
# template = "template.bike"

# Configure random ID generation.
id-charset = "alphanum"
id-length = 4
id-case = "lower"

# EXTRA VARIABLES
[extra]
# key = "value"

# EXTERNAL TOOLS
[tool]
editor = "bike"
pager = "bat --language html --theme Nord"
# pager = "cat | sd '^( )*‣?\\s*<[^>]+>\\s*\\n|(        )?<[^>]+>' '' | sd '    ' '  ' | bat"
fzf-preview = "cat {-1} | sd '^\\s*<[^>]+>\\s*\\n|(        )?<[^>]+>' '' | sd '    ' '  '"
fzf-line = "{{style 'title' filename-stem}} {{style 'understate' body}} {{style 'understate' (json metadata)}}"

fzf-options = """
--tiebreak begin
--exact
--tabstop 2
--height 100%
--layout reverse
--no-hscroll
--no-sort
--preview-window 'right,75%'
"""

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"
sort_by_date = "--sort path-"

# COMMAND ALIASES
[alias]
config = "vim ~/dotfiles/_config/zk/config.toml"
journal = "zk edit -i sort_by_date"
