memodir = "~/Library/CloudStorage/Box-Box/Notes/memo"
editor = "mvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "rg ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "~/kazu/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
